export enum ENameuser {
    "Wellington Felipe Sousa",
    "Carlos Eduardo Silva",
    "João Pedro Santos",
    "Gabriel Henrique Almeida",
    "Bruno César Gomes",
    "Lucas Mateus Barros",
    "Fernando Oliveira",
    "Ricardo Ferreira",
    "Thiago Santos",
    "Bernado Santos",
    "Joao Santos",
    "Windersson Souza Santos",
    "Benedito Souza Santos",
    "Benedito Carlos Santos",
    "Pinho Souza Santos",
    "Elieu Souza Santos",
    "André Almeida",
    "Rafael Costa",
    "Henrique Martins",
    "Eduardo Batista",
    "Fábio Ferreira",
    "Marcelo Gomes",
    "Rodrigo Soares",
    "Leonardo Lima",
    "Renato Nascimento",
    "Antonio Pereira",
    "Felipe Carvalho",
    "Danilo Rocha",
    "Gustavo Fernandes",
    "Miguel Silva",
    "Vinícius Araújo",
    "Francisco Wellington Souza",
    "Francisco Marcos Souza",
    "Francisco Emersson Souza",
    "Marine Wellington Souza",
}
